LEA_ProyectoMultimedia2024_V2/Controllers/MetodoPagoesController.cs
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using LEA_ProyectoMultimedia2024_V2_.Models.Contexts;
    using LEA_ProyectoMultimedia2024_V2_.Models.Tables;
    using LEA_ProyectoMultimedia2024_V2_.Services.Interfaces;
    using LEA_ProyectoMultimedia2024_V2_.Models.DTOs;

    namespace LEA_ProyectoMultimedia2024_V2_.Controllers
    {
        public class MetodoPagoesController : Controller
        {
            private readonly IMetodoDePago _metodoDePago;
            private readonly ICliente _cliente;

            public MetodoPagoesController(IMetodoDePago metodoDePago, ICliente cliente)
            {
                _metodoDePago = metodoDePago;
                _cliente = cliente;
            }

            // GET: MetodoPagoes
            public async Task<IActionResult> Index()
            {
                var metodosPago = await _metodoDePago.GetAllMetodosPagoAsync();
                return View(metodosPago);
            }
            public async Task<IActionResult> ListaMetodoDePago()
            {
                var metodosPago = await _metodoDePago.GetAllMetodosPagoAsync();
                return PartialView(metodosPago);
            }

            // GET: MetodoPagoes/Details/5
            public async Task<IActionResult> PVDetails(int? id)
            {
            var clientes = await _cliente.GetAllClientesAsync();
            ViewData["ClienteId"] = new SelectList(clientes, "ClienteId", "Nombre");
            var metodoPago = await _metodoDePago.GetMetodoPagoByIdAsync(id.Value);
                return PartialView(metodoPago);
            }

            // GET: MetodoPagoes/Create
            public async Task<IActionResult> PVCreateAsync()
            {

            var clientes = await _cliente.GetAllClientesAsync();    
                ViewData["ClienteId"] = new SelectList(clientes, "ClienteId", "Nombre");
                return PartialView();
            }

        // POST: MetodoPagoes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PVCreate([Bind("MetodoPagoId,ClienteId,TipoTarjeta,NumeroTarjeta,FechaExpiracion,Cvv")] MetodoPagoDTO metodoPago)
        {
            if (ModelState.IsValid)
            {
                var DTO = metodoPago.toOriginal();
                await _metodoDePago.CreateMetodoPagoAsync(DTO);

                TempData["SuccessMessage"] = "Método de pago creado exitosamente";
                return RedirectToAction("Index", "Mantenedores");
            }
            else
            {
                var clientes = await _cliente.GetAllClientesAsync();
                ViewData["ClienteId"] = new SelectList(clientes, "ClienteId", "Nombre");
                ModelState.AddModelError("", "Hay errores en el formulario. Por favor, revísalos.");
                return View(metodoPago);
            }
        }


        // GET: MetodoPagoes/Edit/5
        public async Task<IActionResult> PVEdit(int? id)
            {
            ViewData["ClienteId"] = new SelectList(await _metodoDePago.GetClientesAsync(), "ClienteId", "Nombre");
            var metodoPago = await _metodoDePago.GetMetodoPagoByIdAsync(id.Value);
            var metodoPagoDTO = metodoPago.toDto();
                return PartialView(metodoPagoDTO);
            }

        // POST: MetodoPagoes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PVEdit(int id, [Bind("MetodoPagoId,ClienteId,TipoTarjeta,NumeroTarjeta,FechaExpiracion,Cvv")] MetodoPagoDTO metodoPago)
        {
            if (ModelState.IsValid)
            {
                var MetodoPagoOriginal = metodoPago.toOriginal();
                await _metodoDePago.UpdateMetodoPagoAsync(MetodoPagoOriginal);

                // Manejo de solicitud AJAX
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(new { success = true, message = "Método de pago actualizado exitosamente" });
                }
                else
                {
                    TempData["SuccessMessage"] = "Método de pago actualizado exitosamente";
                    return RedirectToAction("Index", "Mantenedores");
                }
            }
            else
            {
                // Obtener los errores de ModelState
                var errors = ModelState
                    .Where(a => a.Value.Errors.Any())
                    .ToDictionary(
                        kvp => kvp.Key,
                        kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToList()
                    );

                // Manejo de solicitud AJAX en caso de error
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(new { success = false, errors });
                }
                else
                {
                    // Regresar la vista con el modelo y los errores de validación
                    ModelState.AddModelError("", "Hay errores en el formulario. Por favor, revísalos.");
                    return View(metodoPago);
                }
            }
        }

        // GET: MetodoPagoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
            {
           

                var metodoPago = await _metodoDePago.GetMetodoPagoByIdAsync(id.Value);

                return PartialView(metodoPago);
            }

            // POST: MetodoPagoes/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                await _metodoDePago.DeleteMetodoPagoAsync(id);
                return RedirectToAction("Index", "Mantenedores");
            }
        }
    }

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/Create.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.DTOs.MetodoPagoDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Crear metodo de pago</h1>


<hr />        
<form asp-action="Create">
<div asp-validation-summary="ModelOnly" class="text-danger"></div>


<div class="row">
    <div class="col-4">

            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control form-select" asp-items="ViewBag.ClienteId"></select>
            </div>
    </div>
    <div class="col-4">
            <div class="form-group">
                <label asp-for="TipoTarjeta" class="control-label"></label>
                <input asp-for="TipoTarjeta" class="form-control" />
                <span asp-validation-for="TipoTarjeta" class="text-danger"></span>
            </div>
    </div>  
    <div class="col-4">
            <div class="form-group">
                <label asp-for="NumeroTarjeta" class="control-label"></label>
                <input asp-for="NumeroTarjeta" class="form-control" />
                <span asp-validation-for="NumeroTarjeta" class="text-danger"></span>
            </div>
    </div>  
    <div class="col-4">
            <div class="form-group">
                <label asp-for="FechaExpiracion" class="control-label"></label>
                <input asp-for="FechaExpiracion" class="form-control" />
                <span asp-validation-for="FechaExpiracion" class="text-danger"></span>
            </div>
    </div> 
    <div class="col-4">
            <div class="form-group">
                <label asp-for="Cvv" class="control-label"></label>
                <input asp-for="Cvv" class="form-control" />
                <span asp-validation-for="Cvv" class="text-danger"></span>
            </div>
    </div>   
 

</div>

<div class="row">

        <div class="col-12 text-end">
            <input type="submit" value="Crear" class="btn btn-success" />
            <a asp-action="Index" class="btn btn-info">Volver</a>
    </div>
</div>

</form>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/Delete.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.Tables.MetodoPago

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Estas seguro/a que quieres eliminar este metodo de pago?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoTarjeta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoTarjeta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroTarjeta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroTarjeta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaExpiracion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaExpiracion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cvv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cvv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MetodoPagoId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">Volver</a>
    </form>
</div>

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/Details.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.Tables.MetodoPago

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del metodo de pago</h1>

<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoTarjeta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoTarjeta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroTarjeta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroTarjeta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaExpiracion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaExpiracion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cvv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cvv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-success" asp-route-id="@Model?.MetodoPagoId">Editar</a> |
    <a asp-action="Index" class="btn btn-info">Volver</a>
</div>

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/Edit.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.Tables.MetodoPago

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar el metodo de pago</h1>


<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="MetodoPagoId" />

<div class="row">
    <div class="col-4">
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control form-select" asp-items="ViewBag.ClienteId"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
    </div>   
    <div class="col-4">
            <div class="form-group">
                <label asp-for="TipoTarjeta" class="control-label"></label>
                <input asp-for="TipoTarjeta" class="form-control" />
                <span asp-validation-for="TipoTarjeta" class="text-danger"></span>
            </div>
    </div>   
    <div class="col-4">
            <div class="form-group">
                <label asp-for="NumeroTarjeta" class="control-label"></label>
                <input asp-for="NumeroTarjeta" class="form-control" />
                <span asp-validation-for="NumeroTarjeta" class="text-danger"></span>
            </div>
    </div>  
    <div class="col-4">
            <div class="form-group">
                <label asp-for="FechaExpiracion" class="control-label"></label>
                <input asp-for="FechaExpiracion" class="form-control" />
                <span asp-validation-for="FechaExpiracion" class="text-danger"></span>
            </div>
    </div>  
    <div class="col-4">
            <div class="form-group">
                <label asp-for="Cvv" class="control-label"></label>
                <input asp-for="Cvv" class="form-control" />
                <span asp-validation-for="Cvv" class="text-danger"></span>
            </div>
    </div>   

</div>
 <div class="row">
        <div class="col-12 text-end">
            <input type="submit" value="Guardar" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-info">Volver</a>
        </div>
 </div>
        </form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/Index.cshtml
@model IEnumerable<LEA_ProyectoMultimedia2024_V2_.Models.Tables.MetodoPago>

@{
    ViewData["Title"] = "Index";
}

<h1>Metodos de pago</h1>

<p>
    <a asp-action="Create" class="btn btn-success d-grid gap-2 d-grid">Crear metodo de pago</a>
</p>
<table class="table" id="Tabla">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TipoTarjeta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroTarjeta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaExpiracion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cvv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TipoTarjeta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroTarjeta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaExpiracion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cvv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente.Nombre)
            </td>
            <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.MetodoPagoId">Editar</a> 
                        <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.MetodoPagoId">Detalles</a> 
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.MetodoPagoId">Eliminar</a>
                </div>

            </td>
        </tr>
}
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            $('#Tabla').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
                }
            });

        });
    </script>
}

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/ListaMetodoDePago.cshtml
@model IEnumerable<LEA_ProyectoMultimedia2024_V2_.Models.Tables.MetodoPago>

@{
    ViewData["Title"] = "Metodos de pago";
}


<p class="text-end mt-4">
    <button asp-action="PVCreate" id="BotonC" class="btn btn-success">Crear metodo de pago</button>
</p>
<table class="table" id="TablaMetodoDePago">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TipoTarjeta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroTarjeta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaExpiracion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cvv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoTarjeta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroTarjeta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaExpiracion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cvv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.Nombre)
                </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button class="btn btn-sm btn-info me-2" onclick="EditMetodoDepago(@item.MetodoPagoId)">Editar</button>
                        <button class="btn btn-sm btn-primary me-2" onclick="DetailsMetodoDePago(@item.MetodoPagoId)">Detalles</button>
                        <button type="button" class="btn btn-danger text-end" onclick="openDeleteModal('@item.MetodoPagoId', '@item.TipoTarjeta')">Eliminar</button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal de Confirmación de Eliminación -->
<div class="modal fade" id="deleteModalMetodoPago" tabindex="-1" aria-labelledby="deleteModalLabelMetodoPago" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"<div style="color: black;" id="deleteModalLabelMetodoPago">Eliminar Metodo de Pago</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"style="color: black;"
                <h3>¿Estás seguro de que quieres eliminar el metodo de pago <strong class="text-danger" id="metodoPagoName"></strong>?</h3>
                <form id="deleteFormMetodoPago" method="post" class="mt-5">
                    <input type="hidden" id="metodoPagoId" name="MetodoPagoId" />
                    <div class="row">
                        <div class="col">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        </div>
                        <div class="col text-end">
                            <input type="submit" value="Eliminar" class="btn btn-danger" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
 

    <script>



        function openDeleteModal(metodoPagoId, metodoPagoName) {
            $('#metodoPagoName').text(metodoPagoName); // Asigna el nombre del metodo de pago al modal
            $('#metodoPagoId').val(metodoPagoId); // Asigna el id del metodo de pago al input oculto
            $('#deleteFormMetodoPago').attr('action', '/MetodoPagoes/Delete/' + metodoPagoId); // Configura la acción del formulario de eliminación
            $('#deleteModalMetodoPago').modal('show'); // Muestra el modal
        }
    </script>

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/PVCreate.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.DTOs.MetodoPagoDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Crear metodo de pago</h1>


<hr />
<form asp-action="PVCreate" id="CCrearUsuario" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>


    <div class="row">
        <div class="col-4">

            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control form-select" asp-items="ViewBag.ClienteId"></select>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="TipoTarjeta" class="control-label"></label>
                <input asp-for="TipoTarjeta" class="form-control"  />
                <span asp-validation-for="TipoTarjeta" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="NumeroTarjeta" class="control-label"></label>
                <input asp-for="NumeroTarjeta" class="form-control"  />
                <span asp-validation-for="NumeroTarjeta" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="FechaExpiracion" class="control-label"></label>
                <input asp-for="FechaExpiracion" class="form-control"  />
                <span asp-validation-for="FechaExpiracion" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Cvv" class="control-label"></label>
                <input asp-for="Cvv" class="form-control"  />
                <span asp-validation-for="Cvv" class="text-danger"></span>
            </div>
        </div>


    </div>

    <div class="row">

        <div class="col-12 text-end">
            <input type="submit" value="Crear" class="btn btn-success" />
            <a asp-action="Index" asp-controller="Mantenedores" class="btn btn-info">Volver</a>
        </div>
    </div>

</form>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $("#CCrearUsuario").on("submit", function (e) {
                e.preventDefault(); // Evitar envío tradicional del formulario

                // Limpiar errores previos
                $("span.text-danger").html("");
                $("input").removeClass("input-validation-error");

                $.ajax({
                    url: '@Url.Action("PVCreate", "MetodoPagoes")',
                    type: 'POST',
                    data: $(this).serialize(),
                    success: function (response) {
                        if (response.success) {
                            alert("Dirección creada exitosamente.");
                            // Realiza alguna acción como redirigir o actualizar la UI
                        } else {
                            // Muestra los errores de validación
                            $.each(response.errors, function (field, messages) {
                                var errorSpan = $("span[data-valmsg-for='" + field + "']");
                                errorSpan.html(messages.join("<br>"));
                                $("input[name='" + field + "']").addClass("input-validation-error");
                            });
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert("Ocurrió un error al procesar la solicitud.");
                    }
                });
            });
        });
    </script>
}

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/PVDetails.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.Tables.MetodoPago

@{
    ViewData["Title"] = "Edit";
}

<h1>Detalles del metodo de pago</h1>


<hr />

    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
            <select asp-for="ClienteId" class="form-control  form-select" asp-items="ViewBag.ClienteId" disabled></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="TipoTarjeta" class="control-label"></label>
            <input asp-for="TipoTarjeta" class="form-control" disabled />
                <span asp-validation-for="TipoTarjeta" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="NumeroTarjeta" class="control-label"></label>
            <input asp-for="NumeroTarjeta" class="form-control" disabled />
                <span asp-validation-for="NumeroTarjeta" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="FechaExpiracion" class="control-label"></label>
            <input asp-for="FechaExpiracion" class="form-control" disabled />
                <span asp-validation-for="FechaExpiracion" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Cvv" class="control-label"></label>
            <input asp-for="Cvv" class="form-control" disabled />
                <span asp-validation-for="Cvv" class="text-danger"></span>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-12 text-end">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        <a asp-action="Index" asp-controller="Mantenedores" class="btn btn-info">Volver</a>
        </div>
    </div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LEA_ProyectoMultimedia2024_V2/Views/MetodoPagoes/PVEdit.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.DTOs.MetodoPagoDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar el metodo de pago</h1>


<hr />
<form asp-action="PVEdit" id="CEdit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="MetodoPagoId" />

    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control form-select" asp-items="ViewBag.ClienteId"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="TipoTarjeta" class="control-label"></label>
                <input asp-for="TipoTarjeta" class="form-control" />
                <span asp-validation-for="TipoTarjeta" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="NumeroTarjeta" class="control-label"></label>
                <input asp-for="NumeroTarjeta" class="form-control" />
                <span asp-validation-for="NumeroTarjeta" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="FechaExpiracion" class="control-label"></label>
                <input asp-for="FechaExpiracion" class="form-control" />
                <span asp-validation-for="FechaExpiracion" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Cvv" class="control-label"></label>
                <input asp-for="Cvv" class="form-control" />
                <span asp-validation-for="Cvv" class="text-danger"></span>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-12 text-end">
            <input type="submit" value="Guardar" class="btn btn-primary" />
            <a asp-action="Index" asp-controller="Mantenedores" class="btn btn-info">Volver</a>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

<script>
    $(document).ready(function () {
        $("#CEdit").on("submit", function (e) {
            e.preventDefault();

            $.ajax({
                url: '@Url.Action("PVEdit", "MetodoPagoes")',
                type: 'POST',
                data: $(this).serialize(),
                success: function (response) {
                    if (response.success) {
                        window.location.href = '@Url.Action("Index", "Mantenedores")';
                    } else {
                        $("span.text-danger").html("");
                        $.each(response.errors, function (key, value) {
                            $('span[data-valmsg-for="' + key + '"]').html(value.join("<br>"));
                        });
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.error("Error en la solicitud AJAX:", textStatus, errorThrown);
                    alert("Ocurrió un error al procesar la solicitud.");
                }
            });
        });
    });
    </script>