LEA_ProyectoMultimedia2024_V2/Models/Tables/Categoria.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LEA_ProyectoMultimedia2024_V2_.Models.Tables;

public partial class Categoria
{
    [Key]
    [Column("CategoriaID")]
    public int CategoriaId { get; set; }

    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(100)]
    public string Descripcion { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Pesokg { get; set; }

    [InverseProperty("Categoria")]
    public virtual ICollection<Producto> Producto { get; set; } = new List<Producto>();
}

LEA_ProyectoMultimedia2024_V2/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LEA_ProyectoMultimedia2024_V2_.Models.Contexts;
using LEA_ProyectoMultimedia2024_V2_.Models.Tables;
using LEA_ProyectoMultimedia2024_V2_.Services.Interfaces;
using LEA_ProyectoMultimedia2024_V2_.Models.DTOs;
using Microsoft.AspNetCore.Authorization;

namespace LEA_ProyectoMultimedia2024_V2_.Controllers
{
    public class CategoriasController : Controller

       
    {

        private readonly ICategorias _categorias;

        public CategoriasController(GimnasioContext context, ICategorias categorias)
        {

         
            _categorias = categorias;
        }


        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            var a = await _categorias.GetCategoriasAsync();
            return View(a);
        }
        public async Task<IActionResult> ListaCategoria()
        {
            var a = await _categorias.GetCategoriasAsync();
            return PartialView(a);
        }

        // GET: Categorias/Details/5
        
        public async Task<IActionResult> PVDetails(int? id)
        {

            var categoria = await _categorias.GetDetails(id.Value);
            return PartialView (categoria);
        }

        // GET: Categorias/Create
        public IActionResult PVCreate()
        {
            return PartialView();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PVCreate([Bind("CategoriaId,Nombre,Descripcion,Pesokg")] CategoriaDTO categoria)
        {
            if (ModelState.IsValid)
            {
                var DTO = categoria.toOriginal();
                await _categorias.AddCategoriaAsync(DTO);
                TempData["SuccessMessage"] = "Cliente creado exitosamente";
                return RedirectToAction("Index", "Mantenedores");
            }
            else
            {
                ModelState.AddModelError("", "Hay errores en el formulario. Por favor, revísalos.");
                return View(categoria);
            }
        }


        // GET: Categorias/Edit/5
        public async Task<IActionResult> PVEdit(int? id)
        {


            var categoria = await _categorias.GetCategoriaByIdAsync(id.Value);
            var CategoriaDto = categoria.ToDto();
            return PartialView(CategoriaDto);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PVEdit(int id, [Bind("CategoriaId,Nombre,Descripcion,Pesokg")] CategoriaDTO categoria)
        {
            if (ModelState.IsValid)
            {
                var CategoriaOriginal = categoria.toOriginal();
                await _categorias.UpdateCategoriaAsync(CategoriaOriginal);

                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(new { success = true, message = "Cliente actualizado exitosamente" });
                }
                else
                {
                    TempData["SuccessMessage"] = "Cliente actualizado exitosamente";
                    return RedirectToAction("Index", "Mantenedores");
                }
            }
            else
            {
                var errors = ModelState
                    .Where(a => a.Value.Errors.Any())
                    .ToDictionary(
                        kvp => kvp.Key,
                        kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToList()
                    );

                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(new { success = false, errors });
                }
                else
                {
                    // Regresar la vista con el modelo y los errores de validación
                    ModelState.AddModelError("", "Hay errores en el formulario. Por favor, revísalos.");
                    return View(categoria);
                }
            }
        }

        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {


            var categoria = await _categorias.GetDetails(id.Value);

            return PartialView(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmede(int id)
        {
           await _categorias.DeleteCategoriaAsync (id);
            return RedirectToAction("Index","Mantenedores");
        }

    }
}

LEA_ProyectoMultimedia2024_V2/Views/Categorias/Create.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.DTOs.CategoriaDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Creador de categorías</h1>

<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Pesokg" class="control-label"></label>
                <input asp-for="Pesokg" class="form-control" />
                <span asp-validation-for="Pesokg" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-end"> 
        <a asp-action="Index" class="btn btn-info">Volver</a>
        <input type="submit" value="Crear Categoria" class=" btn btn-success" />
        </div>
    </div>

</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LEA_ProyectoMultimedia2024_V2/Views/Categorias/Delete.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.Tables.Categoria

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Estas seguro/a que quieres eliminar esta categoria?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pesokg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pesokg)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoriaId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">volver</a>
    </form>
</div>

LEA_ProyectoMultimedia2024_V2/Views/Categorias/Details.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.Tables.Categoria

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles De la categoria</h1>

<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pesokg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pesokg)
        </dd>
    </dl>
</div>
<div>

    <a asp-action="Edit" class="position-relative btn btn-success class=" btn-group"" asp-route-id="@Model?.CategoriaId">Editar</a> |
    <a asp-action="Index" class=" position-relative btn btn-info class=" btn-group"">Volver</a>
</div>

LEA_ProyectoMultimedia2024_V2/Views/Categorias/Edit.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.DTOs.CategoriaDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar categoria</h1>


<hr />

        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CategoriaId" />
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input asp-for="Descripcion" class="form-control" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Pesokg" class="control-label"></label>
                        <input asp-for="Pesokg" class="form-control" />
                        <span asp-validation-for="Pesokg" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12 text-end">
                    <a asp-action="Index" class="btn btn-info">Volver</a>
                    <input type="submit" value="Crear Categoria" class=" btn btn-success" />
                </div>
            </div>

        </form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LEA_ProyectoMultimedia2024_V2/Views/Categorias/Index.cshtml
@model IEnumerable<LEA_ProyectoMultimedia2024_V2_.Models.Tables.Categoria>

@{
    ViewData["Title"] = "Index";
}

<h1>Categorías</h1>
<div> 
<p>
        <a asp-action="Create" class=" btn btn-success d-grid gap-2 d-grid">Crea una categoría</a>
</p>
</div>
<table class="table" id="Tabla">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesokg)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pesokg)
            </td>
            <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a asp-action="Edit" class="btn btn-primary text-end " asp-route-id="@item.CategoriaId">Editar</a>
                        <a asp-action="Details" class="btn btn-warning text-end " asp-route-id="@item.CategoriaId">Detalles</a>
                        <a asp-action="Delete" class="btn btn-danger text-end" asp-route-id="@item.CategoriaId">Eliminar</a>
                </div>

            </td>
        </tr>
}
    </tbody>
</table>


@section scripts
{
    <script>
        $(document).ready(function () {
            $('#Tabla').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
                }
            });

        });
    </script>
}

LEA_ProyectoMultimedia2024_V2/Views/Categorias/ListaCategoria.cshtml
@model IEnumerable<LEA_ProyectoMultimedia2024_V2_.Models.Tables.Categoria>

@{
    ViewData["Title"] = "Categorías";
}


<p class="text-end mt-4">
    <button asp-action="PVCreate" id="BotonC" class="btn btn-success">Crear una categoría</button>
</p>
<table class="table" id="TablaCategoria">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesokg)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pesokg)
                </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button class="btn btn-sm btn-info me-2" onclick="EditCategorias(@item.CategoriaId)">Editar</button>
                        <button class="btn btn-sm btn-primary me-2" onclick="DetailsCategorias(@item.CategoriaId)">Detalles</button>
                        <button type="button" class="btn btn-danger text-end" onclick="openDeleteModalCategoria('@item.CategoriaId', '@item.Nombre')">Eliminar</button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal de Confirmación de Eliminación para Categoría -->
<div class="modal fade" id="deleteModalCategoria" tabindex="-1" aria-labelledby="deleteModalLabelCategoria" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"style="color: black;" id="deleteModalLabelCategoria">Eliminar Categoría</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"style="color: black;"
                <h3>¿Estás seguro de que quieres eliminar la categoría <strong class="text-danger" id="Nombre"></strong>?</h3>
                <form id="deleteFormCategoria" method="post" class="mt-5">
                    <input type="hidden" id="categoriaId" name="CategoriaId" />
                    <div class="row">
                        <div class="col">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        </div>
                        <div class="col text-end">
                            <input type="submit" value="Eliminar" class="btn btn-danger" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    // Función para abrir el modal de eliminación para Categoría
    function openDeleteModalCategoria(CategoriaId, Nombre) {
        $('#Nombre').text(Nombre); // Asigna el nombre de la categoría al modal
        $('#CategoriaId').val(CategoriaId); // Asigna el id de la categoría al input oculto
        $('#deleteFormCategoria').attr('action', '/Categorias/Delete/' + CategoriaId); // Configura la acción del formulario de eliminación
        $('#deleteModalCategoria').modal('show'); // Muestra el modal
    }
</script>

LEA_ProyectoMultimedia2024_V2/Views/Categorias/PVCreate.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.DTOs.CategoriaDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Creador de categorías</h1>

<hr />
<form asp-action="PVCreate" id="CCrearUsuario" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Pesokg" class="control-label"></label>
                <input asp-for="Pesokg" class="form-control"/>
                <span asp-validation-for="Pesokg" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-end">
            <a asp-action="Index" asp-controller="Mantenedores" class="btn btn-info">Volver</a>
            <input type="submit" value="Crear Categoria"  class=" btn btn-success" />
        </div>
    </div>

</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $("#CCrearUsuario").on("submit", function (e) {
                e.preventDefault(); // Evitar envío tradicional del formulario

                // Limpiar errores previos
                $("span.text-danger").html("");
                $("input").removeClass("input-validation-error");

                $.ajax({
                    url: '@Url.Action("PVCreate", "Categorias")',
                    type: 'POST',
                    data: $(this).serialize(),
                    success: function (response) {
                        if (response.success) {
                            alert("Dirección creada exitosamente.");
                            // Realiza alguna acción como redirigir o actualizar la UI
                        } else {
                            // Muestra los errores de validación
                            $.each(response.errors, function (field, messages) {
                                var errorSpan = $("span[data-valmsg-for='" + field + "']");
                                errorSpan.html(messages.join("<br>"));
                                $("input[name='" + field + "']").addClass("input-validation-error");
                            });
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert("Ocurrió un error al procesar la solicitud.");
                    }
                });
            });
        });
    </script>
}

LEA_ProyectoMultimedia2024_V2/Views/Categorias/PVDetails.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.Tables.Categoria

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles De la categoria</h1>


    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control input-disabled" disabled />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
            <input asp-for="Descripcion" class="form-control input-disabled" disabled />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Pesokg" class="control-label"></label>
            <input asp-for="Pesokg" class="form-control input-disabled" disabled />
                <span asp-validation-for="Pesokg" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-end">
            <a asp-action="Index" asp-controller="Mantenedores" class="btn btn-info">Volver</a>
        <button class="btn btn-success" onclick=" EditCategorias(@Model?.CategoriaId)">Editar Categoria</button>

        </div>
    </div>

LEA_ProyectoMultimedia2024_V2/Views/Categorias/PVEdit.cshtml
@model LEA_ProyectoMultimedia2024_V2_.Models.DTOs.CategoriaDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar categoria</h1>


<hr />

<form asp-action="PVEdit" id="CEdit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CategoriaId" />
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Pesokg" class="control-label"></label>
                <input asp-for="Pesokg" class="form-control" />
                <span asp-validation-for="Pesokg" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-end">
            <a asp-action="Index" asp-controller="Mantenedores" class="btn btn-info">Volver</a>
            <input type="submit" value="Crear Categoria" class=" btn btn-success" />
        </div>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $("#CEdit").on("submit", function (e) {
                e.preventDefault();

                $.ajax({
                    url: '@Url.Action("PVEdit", "Categorias")',
                    type: 'POST',
                    data: $(this).serialize(),
                    success: function (response) {
                        if (response.success) {
                            window.location.href = '@Url.Action("Index", "Mantenedores")';
                        } else {
                            $("span.text-danger").html("");
                            $.each(response.errors, function (key, value) {
                                $('span[data-valmsg-for="' + key + '"]').html(value.join("<br>"));
                            });
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.error("Error en la solicitud AJAX:", textStatus, errorThrown);
                        alert("Ocurrió un error al procesar la solicitud.");
                    }
                });
            });
        });

    </script>
}